### ISSUE TITLE
Admins

### ISSUE THREAD

**Issue by fabiomferreira** [beerjs/cgr#2]
Only Igor is admin. Could someone put the others as admins too? @jordanpapaleo

**Comment by jordanpapaleo** [comment]
![image](https://user-images.githubusercontent.com/1728807/51848330-40f84600-22d2-11e9-8d99-d532d54eae9b.png)

Only Igor has accepted his invitation.

**Comment by fabiomferreira** [comment]
Sorry about that. Now I see

**Comment by jordanpapaleo** [comment]
No worries at all!  Are you able to get in now?

**Comment by fabiomferreira** [comment]
Yeah, thanks a lot!
