### ISSUE TITLE
Encontro BeerJS #5

### ISSUE THREAD

**Issue by fabiomferreira** [beerjs/cgr#7]
- **Local**: [Bar Mercearia](https://goo.gl/maps/5LVwwF2FRhC2)
- **Data**: 07/12/2019
- **Hora**: 17h00m

Insira o evento no seu Google Calendar no link abaixo.
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=MTJmcTlidnFubnZvMDNzN2gwanVvNWxpZ2EgZmFiaW9tYXRhZmVycmVpcmFAbQ&amp;tmsrc=fabiomataferreira%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_pt-BR.gif"></a>

**Comment by gabrielmedina** [comment]
Pô, só vi isso agora :/
Bora marcar o primeiro de 2020!
